### ISSUE TITLE
Incorrect GetPayload() and GetPayloadSize()

### ISSUE THREAD

**Issue by Scovadi** [hyle-team/tor-connect#4]
There are issues with GetPayload() and GetPayloadSize(). While debugging (HTTP request to api.ipify.org) the actual data offset to the HTTP response was +16 according to relay_node->GetBuffer():
https://github.com/hyle-team/tor-connect/blob/784778f9ab02f0bd17a86af6945c7ed6368f25bf/torlib/torlib.cpp#L156
The relay_node->GetPayload() on the other hand always returns offset +5 (POSITION_PAYLOAD_SIZE) which is a mismatch of 11 bytes. Also small responses are always padded to 514 bytes (CELL_SIZE) and relay_node->GetPayloadSize() is hardcoded to return 509 bytes (CELL_SIZE - POSITION_PAYLOAD_SIZE) even if the actual payload is smaller.
https://github.com/hyle-team/tor-connect/blob/784778f9ab02f0bd17a86af6945c7ed6368f25bf/torlib/torlib.cpp#L160
See attached a screenshot with log level debug.
![tor-connect-screen](https://user-images.githubusercontent.com/99340933/153221798-0c945b89-a463-4bcc-a932-7c62c19cdcc0.png)

**Comment by cryptozoidberg** [comment]
@bml505  would you like to take a look into it?

**Comment by Scovadi** [comment]
Looks like GetPayload() and GetPayloadLength() need to be replaced by the equivalents from Relay, but then there is still a mismatch in offset of 2 bytes
https://github.com/hyle-team/tor-connect/blob/784778f9ab02f0bd17a86af6945c7ed6368f25bf/torlib/torlib.cpp#L160

`data_result.append(reinterpret_cast<char const*>(relay_node->GetRelayPayload()+2), relay_node->GetRelayPayloadLength());`

If you look at RelayCell::GetRelayPayload() and RelayCell::GetRelayPayloadLength() they both access the same address. You should set RELAY_PAYLOADSIZE_OFFSET to (14) and set RELAY_PAYLOAD_OFFSET at (16). I made a pull request for this

**Comment by bml505** [comment]
Yes you are right, it is better to use GetRelayPayload and GetRelayPayloadLength here. In this case you get the whole cell together with the service data. RELAY_PAYLOADSIZE_OFFSET should stay that way, I will add the unaccounted Relay length and make an offset relative to that.

**Comment by Scovadi** [comment]
RC05 by BML505 fixes this issue
