### ISSUE TITLE
Any plans on including HS support as a thin TOR client

### ISSUE THREAD

**Issue by Scovadi** [hyle-team/tor-connect#9]
No support for finding introduction point via HSDir, only traffic via exit node
https://github.com/hyle-team/tor-connect/blob/a68ab97d6ce05c78cbe1ea43e499ad38ddfd7341/torlib/torlib.cpp#L263

**Comment by bml505** [comment]
There are no plans to expand the node search in the library in the near future.

**Comment by Scovadi** [comment]
Thanks
